In [8]:

import pandas as pd
import json
path = "/Users/sefika/phd_projects/llm-catastrophic-re/results_all/results_rationale_nli/gemini/tacred_mas_top_prob_5/llm_judged_results.json"

In [9]:
def read_json(file_path):
    with open(file_path, "r") as f:
        return json.load(f)

def analyze_tacred_mas(data):
    llm_judged = [item['llm_judged'] for item in data]
    return llm_judged

In [10]:
tacred_mas = analyze_tacred_mas(read_json(path))
tacred_mas_df = pd.DataFrame(tacred_mas)
tacred_mas_df.T.head()

                       0     1     2     3     4
total_human_judged  3325  3325  3325  3325  3325
correctly_judged     151   336   234   376   196
false_positives      159   349   253   421   217

In [11]:
fewrel_path = "/Users/sefika/phd_projects/llm-catastrophic-re/results_all/results_rationale_nli/gemini/fewrel_mas_top_prob_5/llm_judged_results.json"

fewrel = analyze_tacred_mas(read_json(fewrel_path))
fewrel_df = pd.DataFrame(fewrel)
fewrel_df.T.head()

                        0      1      2      3      4
total_human_judged  11200  11200  11200  11200  11200
correctly_judged     1370   1580   1722   1045   1336
false_positives      1656   1857   1949   1271   1615